spring.application.name=scribbleIoClone
server.port=9090
spring.data.mongodb.auto-index-creation=true
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.mongodb.uri=${MONGODB_URI}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
file.upload-dir=/uploads