spring.application.name=scribbleIoClone
server.port=9090
spring.data.mongodb.auto-index-creation=true
spring.redis.host=localhost
spring.redis.port=6379
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=scribbleIoClone
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
file.upload-dir=C:/Users/Mecklon Fernandes/Desktop/code/scribbleIoClone/backend/uploads