spring.application.name=scribbleIoClone

server.port=${PORT:9090}

spring.data.mongodb.auto-index-creation=true

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=scribbleIoClone

spring.data.redis.url=${REDIS_URL}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

file.upload-dir=/uploads